#! /usr/bin/env bash
# shellcheck disable=SC1091
eval "$(. _tf_aux_functions)"

IDs_JSON="${1:--}"

jq -r ' .[] |
    "tf state rm \"\(.name)\";\n  tf import \"\(.name)\"% \"\(.id)\";"
' "$IDs_JSON" \
| awk '{printf "%s%s\n", (NR==1 ? "#! /usr/bin/env bash\n\n" : ""), $0;}' \
| column -ts'%'

eval "$( _tf_exit_code )"
